In [9]:
!pip install pyspark

from google.colab import drive
drive.mount('/content/drive')

import pyspark.sql.functions as f
from pyspark.sql import SparkSession
from pyspark.sql.types import StructType, IntegerType, StringType, FloatType, StructField,BooleanType

schema = StructType([
    StructField("CrimeRate", FloatType(), True), 
    StructField("Youth", IntegerType(), True), 
    StructField("Southern", IntegerType(), True), 
    StructField("Education", FloatType(), True), 
    StructField("ExpenditureYear0", IntegerType(), True), 
    StructField("LabourForce", IntegerType(), True), 
    StructField("Males", IntegerType(), True), 
    StructField("MoreMales", IntegerType(), True), 
    StructField("StateSize", IntegerType(), True), 
    StructField("YouthUnemployment", IntegerType(), True), 
    StructField("MatureUnemployment", IntegerType(), True),
    StructField("HighYouthUnemploy", IntegerType(), True),
    StructField("Wage", IntegerType(), True),
    StructField("BelowWage", IntegerType(), True)
    ])

spark = SparkSession.builder.appName("Сrime").getOrCreate()
df = spark.read.format("csv").option("header", True).schema(schema).load("Crime.csv")
df.printSchema()
df.show()

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pyspark in /usr/local/lib/python3.8/dist-packages (3.3.1)
Requirement already satisfied: py4j==0.10.9.5 in /usr/local/lib/python3.8/dist-packages (from pyspark) (0.10.9.5)
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
root
 |-- CrimeRate: float (nullable = true)
 |-- Youth: integer (nullable = true)
 |-- Southern: integer (nullable = true)
 |-- Education: float (nullable = true)
 |-- ExpenditureYear0: integer (nullable = true)
 |-- LabourForce: integer (nullable = true)
 |-- Males: integer (nullable = true)
 |-- MoreMales: integer (nullable = true)
 |-- StateSize: integer (nullable = true)
 |-- YouthUnemployment: integer (nullable = true)
 |-- MatureUnemployment: integer (nullable = true)
 |-- HighYouthUnemploy: integer (nullable = true)
 |-- Wage: integer (nullable = true)
 |-- BelowWage: integer (nullable = true)

+---------+-----+--------+---------+----------------+-----------+-----+---------+---------+-----------------+------------------+-----------------+----+---------+
|CrimeRate|Youth|Southern|Education|ExpenditureYear0|LabourForce|Males|MoreMales|StateSize|YouthUnemployment|MatureUnemployment|HighYouthUnemploy|Wage|BelowWage|
+---------+-----+--------+---------+----------------+-----------+-----+---------+---------+-----------------+------------------+-----------------+----+---------+
|     45.5|  135|       0|     12.4|              69|        540|  965|        0|        6|               80|                22|                1| 564|      139|
|     52.3|  140|       0|     10.9|              55|        535| 1045|        1|        6|              135|                40|                1| 453|      200|
|     56.6|  157|       1|     11.2|              47|        512|  962|        0|       22|               97|                34|                0| 288|      276|
|     60.3|  139|       1|     11.9|              46|        480|  968|        0|       19|              135|                53|                0| 457|      249|
|     64.2|  126|       0|     12.2|             106|        599|  989|        0|       40|               78|                25|                1| 593|      171|
|     67.6|  128|       0|     13.5|              67|        624|  972|        0|       28|               77|                25|                1| 507|      206|
|     70.5|  130|       0|     14.1|              63|        641|  984|        0|       14|               70|                21|                1| 486|      196|
|     73.2|  143|       0|     12.9|              66|        537|  977|        0|       10|              114|                35|                1| 487|      166|
|     75.0|  141|       0|     12.9|              56|        523|  968|        0|        4|              107|                37|                0| 489|      170|
|     78.1|  133|       0|     11.4|              51|        599| 1024|        1|        7|               99|                27|                1| 425|      225|
|     79.8|  142|       1|     12.9|              45|        533|  969|        0|       18|               94|                33|                0| 318|      250|
|     82.3|  123|       0|     12.5|              97|        526|  948|        0|      113|              124|                50|                0| 572|      158|
|     83.1|  135|       0|     13.6|              62|        595|  986|        0|       22|               77|                27|                0| 529|      190|
|     84.9|  121|       0|     13.2|             118|        547|  964|        0|       25|               84|                29|                0| 689|      126|
|     85.6|  166|       1|     11.4|              58|        521|  973|        0|       46|               72|                26|                0| 396|      237|
|     88.0|  140|       0|     12.9|              71|        632| 1029|        1|        7|              100|                24|                1| 526|      174|
|     92.3|  126|       0|     12.7|              74|        602|  984|        0|       34|              102|                33|                1| 557|      195|
|     94.3|  130|       0|     13.3|             128|        536|  934|        0|       51|               78|                34|                0| 627|      135|
|     95.3|  125|       0|     12.0|              90|        586|  964|        0|       97|              105|                43|                0| 617|      163|
|     96.8|  151|       1|     10.0|              58|        510|  950|        0|       33|              108|                41|                0| 394|      261|
+---------+-----+--------+---------+----------------+-----------+-----+---------+---------+-----------------+------------------+-----------------+----+---------+
only showing top 20 rows

In [13]:
print("Завдання 1")
print("Створити нову таблицю, яка буде містити наступні два стовпці: витрати на поліцію (розбити весь діапазон на десять частин); масив кількості чоловіків на 1000 нас, що відповідають цій частоті.")

from pyspark.sql.functions import array
from pyspark.sql.functions import col
from pyspark.sql.functions import split
from pyspark.sql.functions import lit
from pyspark.sql.functions import explode

df.createOrReplaceTempView("View")
df2 = spark.sql("SELECT ExpenditureYear0, collect_set(Males) AS Males FROM View GROUP BY ExpenditureYear0 ORDER BY ExpenditureYear0")
df2.show()

print("Завдання 2")
print("Взяти таблицю з завдання 1 і перетворити другий стовпець на кілька стовпців.")

df3 = df2.select("ExpenditureYear0", df2.Males[0], df2.Males[1], df2.Males[2]).show()

Завдання 1
Створити нову таблицю, яка буде містити наступні два стовпці: витрати на поліцію (розбити весь діапазон на десять частин); масив кількості чоловіків на 1000 нас, що відповідають цій частоті.
+----------------+---------------+
|ExpenditureYear0|          Males|
+----------------+---------------+
|              45|          [969]|
|              46|          [968]|
|              47|          [962]|
|              51|         [1024]|
|              55|         [1045]|
|              56|          [968]|
|              57|          [986]|
|              58|[974, 950, 973]|
|              61|          [953]|
|              62|          [986]|
|              63|     [984, 972]|
|              65|          [955]|
|              66|          [977]|
|              67|          [972]|
|              69|          [965]|
|              71|         [1029]|
|              72|          [998]|
|              74|          [984]|
|              75|     [996, 972]|
|              78|         [1038]|
+----------------+---------------+
only showing top 20 rows

Завдання 2
Взяти таблицю з завдання 1 і перетворити другий стовпець на кілька стовпців.
+----------------+--------+--------+--------+
|ExpenditureYear0|Males[0]|Males[1]|Males[2]|
+----------------+--------+--------+--------+
|              45|     969|    null|    null|
|              46|     968|    null|    null|
|              47|     962|    null|    null|
|              51|    1024|    null|    null|
|              55|    1045|    null|    null|
|              56|     968|    null|    null|
|              57|     986|    null|    null|
|              58|     974|     950|     973|
|              61|     953|    null|    null|
|              62|     986|    null|    null|
|              63|     984|     972|    null|
|              65|     955|    null|    null|
|              66|     977|    null|    null|
|              67|     972|    null|    null|
|              69|     965|    null|    null|
|              71|    1029|    null|    null|
|              72|     998|    null|    null|
|              74|     984|    null|    null|
|              75|     996|     972|    null|
|              78|    1038|    null|    null|
+----------------+--------+--------+--------+
only showing top 20 rows

In [15]:
print("Завдання 3")
print("Знайти середню частоту злочинів для усіх можливих поєднань параметрів Southern та HighYouthUnemploy.")

from pyspark.sql.functions import col, avg
import numpy as np
from pyspark.sql.functions import udf
from pyspark.sql.types import FloatType
from pyspark.sql.functions import expr


df.createOrReplaceTempView("View")
df4 = spark.sql("SELECT Southern, HighYouthUnemploy, collect_set(CrimeRate) AS CrimeRate FROM View GROUP BY Southern, HighYouthUnemploy ORDER BY Southern, HighYouthUnemploy")

query = """aggregate(
    `{col}`,
    CAST(0.0 AS double),
    (acc, x) -> acc + x,
    acc -> acc / size(`{col}`)
) AS  `avg_{col}`""".format(col="CrimeRate")

df4.selectExpr("*", query).show()

Завдання 3
Знайти середню частоту злочинів для усіх можливих поєднань параметрів Southern та HighYouthUnemploy.
+--------+-----------------+--------------------+------------------+
|Southern|HighYouthUnemploy|           CrimeRate|     avg_CrimeRate|
+--------+-----------------+--------------------+------------------+
|       0|                0|[127.2, 104.3, 11...|116.45294234331917|
|       0|                1|[67.6, 64.2, 115....| 88.67142731802804|
|       1|                0|[98.7, 96.8, 99.9...| 99.28666661580404|
|       1|                1|             [121.6]| 121.5999984741211|
+--------+-----------------+--------------------+------------------+

In [26]:
print("Завдання 4")
print("Додати в таблицю Crime новий стовпець, що містить різницю між") 
print("середнім та поточним значенням витрат на поліцію в залежності від")
print("того чи південний штат. Наприклад, якщо середні витрати в")
print("південних штатах 355, а в першому рядку витрати 300 і це південний") 
print("штат, то значення в додатковому стовпчику = 355-300=55. Зберегти") 
print("новий файл.")


import pyspark.sql.functions as f
import pandas as pd
from pyspark.sql import SparkSession
from pyspark.sql.types import StructType, IntegerType, StringType, FloatType, StructField,BooleanType

schema = StructType([
    StructField("CrimeRate", FloatType(), True), 
    StructField("Youth", IntegerType(), True), 
    StructField("Southern", IntegerType(), True), 
    StructField("Education", FloatType(), True), 
    StructField("ExpenditureYear0", IntegerType(), True), 
    StructField("LabourForce", IntegerType(), True), 
    StructField("Males", IntegerType(), True), 
    StructField("MoreMales", IntegerType(), True), 
    StructField("StateSize", IntegerType(), True), 
    StructField("YouthUnemployment", IntegerType(), True), 
    StructField("MatureUnemployment", IntegerType(), True),
    StructField("HighYouthUnemploy", IntegerType(), True),
    StructField("Wage", IntegerType(), True),
    StructField("BelowWage", IntegerType(), True)
    ])

spark = SparkSession.builder.appName("Сrime").getOrCreate()
df = spark.read.format("csv").option("header", True).schema(schema).load("Crime.csv")

df10 = spark.sql("SELECT avg(ExpenditureYear0) AS avg_ExpenditureYear0_Southern FROM View GROUP BY Southern ORDER BY Southern")
df10.show()

tab1 = df.filter(df.Southern == 0).withColumn("ExpenditureYear0_avg-ExpenditureYear0", (92 - df.ExpenditureYear0))
tab2 = df.filter(df.Southern == 1).withColumn("ExpenditureYear0_avg-ExpenditureYear0", (94 - df.ExpenditureYear0))
df9 = tab1.union(tab2)
df9.toPandas().to_csv("Crime2.csv")
df9.show(n=47)

Завдання 4
Додати в таблицю Crime новий стовпець, що містить різницю між
середнім та поточним значенням витрат на поліцію в залежності від
того чи південний штат. Наприклад, якщо середні витрати в
південних штатах 355, а в першому рядку витрати 300 і це південний
штат, то значення в додатковому стовпчику = 355-300=55. Зберегти
новий файл.
+-----------------------------+
|avg_ExpenditureYear0_Southern|
+-----------------------------+
|            92.87096774193549|
|                        69.75|
+-----------------------------+

+---------+-----+--------+---------+----------------+-----------+-----+---------+---------+-----------------+------------------+-----------------+----+---------+-------------------------------------+
|CrimeRate|Youth|Southern|Education|ExpenditureYear0|LabourForce|Males|MoreMales|StateSize|YouthUnemployment|MatureUnemployment|HighYouthUnemploy|Wage|BelowWage|ExpenditureYear0_avg-ExpenditureYear0|
+---------+-----+--------+---------+----------------+-----------+-----+---------+---------+-----------------+------------------+-----------------+----+---------+-------------------------------------+
|     45.5|  135|       0|     12.4|              69|        540|  965|        0|        6|               80|                22|                1| 564|      139|                                   23|
|     52.3|  140|       0|     10.9|              55|        535| 1045|        1|        6|              135|                40|                1| 453|      200|                                   37|
|     64.2|  126|       0|     12.2|             106|        599|  989|        0|       40|               78|                25|                1| 593|      171|                                  -14|
|     67.6|  128|       0|     13.5|              67|        624|  972|        0|       28|               77|                25|                1| 507|      206|                                   25|
|     70.5|  130|       0|     14.1|              63|        641|  984|        0|       14|               70|                21|                1| 486|      196|                                   29|
|     73.2|  143|       0|     12.9|              66|        537|  977|        0|       10|              114|                35|                1| 487|      166|                                   26|
|     75.0|  141|       0|     12.9|              56|        523|  968|        0|        4|              107|                37|                0| 489|      170|                                   36|
|     78.1|  133|       0|     11.4|              51|        599| 1024|        1|        7|               99|                27|                1| 425|      225|                                   41|
|     82.3|  123|       0|     12.5|              97|        526|  948|        0|      113|              124|                50|                0| 572|      158|                                   -5|
|     83.1|  135|       0|     13.6|              62|        595|  986|        0|       22|               77|                27|                0| 529|      190|                                   30|
|     84.9|  121|       0|     13.2|             118|        547|  964|        0|       25|               84|                29|                0| 689|      126|                                  -26|
|     88.0|  140|       0|     12.9|              71|        632| 1029|        1|        7|              100|                24|                1| 526|      174|                                   21|
|     92.3|  126|       0|     12.7|              74|        602|  984|        0|       34|              102|                33|                1| 557|      195|                                   18|
|     94.3|  130|       0|     13.3|             128|        536|  934|        0|       51|               78|                34|                0| 627|      135|                                  -36|
|     95.3|  125|       0|     12.0|              90|        586|  964|        0|       97|              105|                43|                0| 617|      163|                                    2|
|    104.3|  134|       0|     12.5|              75|        595|  972|        0|       47|               83|                31|                0| 580|      172|                                   17|
|    105.9|  130|       0|     13.4|              90|        623| 1049|        1|        3|              113|                40|                0| 588|      160|                                    2|
|    107.2|  148|       0|     13.7|              72|        601|  998|        0|        9|               84|                20|                1| 590|      144|                                   20|
|    108.3|  126|       0|     13.8|              97|        542|  990|        0|       18|              102|                35|                0| 589|      166|                                   -5|
|    115.1|  131|       0|     13.7|              78|        574| 1038|        1|        7|              142|                42|                1| 540|      176|                                   14|
|    117.2|  136|       0|     12.9|              95|        574| 1012|        1|       29|              111|                37|                1| 622|      162|                                   -3|
|    119.7|  119|       0|     11.9|             166|        521|  938|        0|      168|               92|                36|                0| 637|      154|                                  -74|
|    127.2|  132|       0|     10.4|              87|        564|  953|        0|       43|               83|                32|                0| 513|      227|                                    5|
|    132.4|  152|       0|     12.0|              82|        571| 1018|        1|       10|              103|                28|                1| 537|      215|                                   10|
|    135.5|  125|       0|     12.5|             113|        567|  985|        0|       78|              130|                58|                0| 626|      166|                                  -21|
|    137.8|  141|       0|     14.2|             109|        591|  985|        0|       18|               91|                20|                1| 578|      174|                                  -17|
|    140.8|  150|       0|     12.0|             109|        531|  964|        0|        9|               87|                38|                0| 559|      153|                                  -17|
|    149.3|  143|       0|     12.3|             103|        583| 1012|        1|       13|               96|                36|                0| 557|      194|                                  -11|
|    154.3|  124|       0|     12.3|             121|        580|  966|        0|      101|               77|                35|                0| 657|      170|                                  -29|
|    157.7|  136|       0|     15.1|             149|        577|  994|        0|      157|              102|                39|                0| 673|      167|                                  -57|
|    161.8|  131|       0|     13.2|             160|        631| 1071|        1|        3|              102|                41|                0| 674|      152|                                  -68|
|     56.6|  157|       1|     11.2|              47|        512|  962|        0|       22|               97|                34|                0| 288|      276|                                   47|
|     60.3|  139|       1|     11.9|              46|        480|  968|        0|       19|              135|                53|                0| 457|      249|                                   48|
|     79.8|  142|       1|     12.9|              45|        533|  969|        0|       18|               94|                33|                0| 318|      250|                                   49|
|     85.6|  166|       1|     11.4|              58|        521|  973|        0|       46|               72|                26|                0| 396|      237|                                   36|
|     96.8|  151|       1|     10.0|              58|        510|  950|        0|       33|              108|                41|                0| 394|      261|                                   36|
|     97.4|  152|       1|     10.8|              57|        530|  986|        0|       30|               92|                43|                0| 405|      264|                                   37|
|     98.7|  162|       1|     12.1|              75|        522|  996|        0|       40|               73|                27|                0| 496|      224|                                   19|
|     99.9|  149|       1|     10.7|              61|        515|  953|        0|       36|               86|                35|                0| 395|      251|                                   33|
|    103.0|  177|       1|     11.0|              58|        638|  974|        0|       24|               76|                28|                0| 382|      254|                                   36|
|    106.6|  157|       1|     11.1|              65|        553|  955|        0|       39|               81|                28|                0| 421|      239|                                   29|
|    109.4|  135|       1|     11.4|             123|        537|  978|        0|       31|               89|                34|                0| 631|      165|                                  -29|
|    112.1|  142|       1|     10.9|              81|        497|  956|        0|       33|              116|                47|                0| 427|      247|                                   13|
|    114.3|  127|       1|     12.8|              82|        519|  982|        0|        4|               97|                38|                0| 620|      168|                                   12|
|    121.6|  147|       1|     13.9|              63|        560|  972|        0|       23|               76|                24|                1| 462|      233|                                   31|
|    123.4|  145|       1|     11.7|              82|        560|  981|        0|       96|               88|                31|                0| 488|      228|                                   12|
|    145.4|  131|       1|     12.2|             115|        542|  969|        0|       50|               79|                35|                0| 472|      206|                                  -21|
+---------+-----+--------+---------+----------------+-----------+-----+---------+---------+-----------------+------------------+-----------------+----+---------+-------------------------------------+